name: Deployment trigger

on:
  push:
    branches:
      - main

jobs:
  visit-url:
    runs-on: ubuntu-latest

    steps:
      - name: Visit External URL
        run: |
          curl -sL https://deploy.aneural.org/research > /dev/null
